### ISSUE TITLE
Symfony 4.x support?

### ISSUE THREAD

**Issue by tarlepp** [auth0-community/auth0-symfony-api-samples#17]
Seems like this currently there is only example for Symfony 3.x, where is the example for Symfony 4.x ?

**Comment by jerdog** [comment]
We discussed that [here](https://community.auth0.com/t/symfony-4-quick-start-guide-update-eta/15744) with the following:

>At this time we do not have it slated to update to Symfony v4 but we welcome any PRs to assist in that endeavor. I did receive feedback from one of our engineers that he was able to upgrade a v3 install to v4 with this module included, but starting with v4 was not working.....

**Comment by tarlepp** [comment]
@jerdog thanks for quick feedback

I'm having today "labday" (in our company we get one day per month to "educate/learn new/etc") so I think that I could take a look to provide that PR - although I won't promise that :D

**Comment by jerdog** [comment]
That would be great - and the very definition of community-maintained @tarlepp !

**Comment by beardaway** [comment]
Hey there @tarlepp have you managed to get some working language upgrade? As Jeremy said we don't have any plans for updating it but we are super open for supporting any community efforts!

**Comment by tarlepp** [comment]
@beardaway sorry I have've been just too busy @work and then totally exhausted on evenings.

I would suggest to add "help wanted" tag to issue.

**Comment by beardaway** [comment]
Sure no worries! Thanks a lot for clear communication!

**Comment by beardaway** [comment]
Closing this as of now as we still do not have enough bandwidth to take care of that. We're in the process of establishing a maintenance strategy for those repose once we have it we will potentially get back to this issue! Thanks you for understanding!
