### ISSUE TITLE
WebserviceUser is not defined

### ISSUE THREAD

**Issue by Franky238** [auth0-community/auth0-symfony-api-samples#30]
I cannot find definition of WebserviceUser so I used A0User. Is it ok? 

https://github.com/auth0-community/auth0-symfony-api-samples/blob/38e2b573e3bb24e2b98927a57596c43be684f21d/01-Authorization-RS256/src/AppBundle/Security/A0UserProvider.php#L58

**Comment by JimCMorrison** [comment]
After reviewing as a team we’ve decided to deprecate this repository 
in favor of focusing on more actively leveraged projects. We will be 
closing all open issues and pull requests, as a result of these changes.  
If you need any further help from our team you can reach out at 
[Community.Auth0.com](https://community.auth0.com/) -- Thank you for your contributions.
