### ISSUE TITLE
Outdated dependency

### ISSUE THREAD

**Issue by paulioceano** [auth0-community/auth0-symfony-api-samples#4]
In the composer.json file, the Symfony version is 3.2, the latest version is 3.3

![3390-2](https://user-images.githubusercontent.com/15818783/28763414-df786562-758b-11e7-80de-855804279e1c.png)

AUTH-3390

**Comment by beardaway** [comment]
Hey there!

Sorry that you needed to wait for so long. We're gradually planning adding improvements to the developer experience we offer here in the org and sometimes simply face people resources bandwidth.  We just merged the PR that took care of that!
